services:
  backend:
    image: henriquecmelo/drinkrats-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: henriquecmelo/drinkrats-frontend:latest
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
